package coreUtils.base;

import android.Manifest;
import android.annotation.SuppressLint;
import android.content.Context;
import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.content.pm.PackageManager;
import android.content.res.Configuration;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.VibrationEffect;
import android.os.Vibrator;
import android.os.VibratorManager;
import android.provider.Settings;
import android.view.LayoutInflater;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import androidx.viewbinding.ViewBinding;

import coreUtils.library.process.AppDirsValidator;
import coreUtils.library.process.LocaleHelper;
import coreUtils.library.process.LoggerUtils;
import coreUtils.library.storage.FileStorageUtility;

/**
 * Abstract base activity that provides common functionality for all app screens,
 * including view binding integration, orientation locking, crash handling,
 * directory validation, and permission management. The type parameter {@code VB}
 * represents the specific view binding class generated for each activity's layout.
 *
 * <p><strong>Core responsibilities:</strong>
 * <ul>
 * <li>Manages a type-safe view binding instance for the activity's layout.</li>
 * <li>Applies saved language preferences via {@link #attachBaseContext(Context)}.</li>
 * <li>Registers a global crash handler to catch uncaught exceptions.</li>
 * <li>Validates required application directories on creation.</li>
 * <li>Handles configuration changes including night mode and orientation.</li>
 * <li>Provides permission request methods for storage, notifications, and file access.</li>
 * <li>Implements haptic feedback utilities for UI interactions.</li>
 * </ul>
 *
 * <p><strong>Subclass requirements:</strong>
 * Subclasses must implement {@link #inflateBinding(LayoutInflater)} to provide
 * the specific binding for their layout, {@link #onLoadedLayout()} for post-inflation
 * initialization, and {@link #shouldLockOrientation()} to control screen rotation
 * behavior. Subclasses may also override permission check methods as needed.
 *
 * <p><strong>Lifecycle integration:</strong>
 * The activity enforces a strict initialization order in {@link #onCreate(Bundle)}:
 * orientation lock → super call → crash handler → directory validation → set content
 * view → post-load initialization. This ensures consistent behavior across all
 * derived activities.
 *
 * @param <VB> The view binding type generated by the Android Gradle plugin for
 *             a specific layout resource (e.g., {@code ActivityMainBinding}).
 * @see androidx.appcompat.app.AppCompatActivity
 * @see androidx.viewbinding.ViewBinding
 */
public abstract class BaseActivity<VB extends ViewBinding> extends AppCompatActivity {
	private final LoggerUtils logger = LoggerUtils.from(getClass());
	
	protected static final int REQUEST_CODE_POST_NOTIFICATIONS = 101;
	protected static final int REQUEST_CODE_STORAGE_PERMISSION = 102;
	protected static final int REQUEST_CODE_MANAGE_STORAGE = 103;
	protected static final int REQUEST_CODE_INSTALL_PACKAGES = 104;
	
	protected VB binding;
	
	/**
	 * Inflates the activity's layout using view binding and returns the generated
	 * binding instance. Subclasses must implement this method to provide the
	 * type-safe binding object specific to their layout file. The binding is typically
	 * generated by the Android Gradle plugin from the layout XML resource.
	 *
	 * <p><strong>Implementation pattern:</strong>
	 * The concrete implementation should call the static {@code inflate()} method on
	 * the generated binding class, passing the provided {@link LayoutInflater}.
	 * Example: {@code return ActivityMainBinding.inflate(inflater);}
	 *
	 * <p>The returned binding is stored in a protected field (typically named
	 * {@code binding}) and used in {@link #setContentView()} to set the activity's
	 * root view. It also provides type-safe access to all views defined in the layout.
	 *
	 * @param inflater The layout inflater service used to create view hierarchies
	 *                 from XML layout resources. Typically obtained via
	 *                 {@link android.app.Activity#getLayoutInflater()}.
	 * @return The view binding instance containing references to all views in the
	 * inflated layout. The type parameter {@code VB} is defined at the
	 * class level and represents the specific binding class.
	 * @see #setContentView()
	 * @see #onLoadedLayout()
	 */
	protected abstract VB inflateBinding(LayoutInflater inflater);
	
	/**
	 * Performs post-layout initialization logic after the content view has been
	 * inflated and set. Subclasses must implement this method to configure views,
	 * set up listeners, load data, or execute any initialization that requires
	 * the UI hierarchy to be fully created.
	 *
	 * <p><strong>Execution timing:</strong>
	 * This method is invoked at the end of {@link #onCreate(Bundle)} after
	 * {@link #setContentView()} has been called and the binding views are available.
	 * It is analogous to calling {@link android.app.Activity#findViewById(int)} after
	 * setting the content view, but provides a cleaner separation of responsibilities
	 * in this base activity class.
	 *
	 * <p>Subclasses should assume that all views referenced in the binding instance
	 * are non-null and ready for interaction. Avoid performing long-running
	 * operations here; delegate those to a background thread or a ViewModel.
	 *
	 * @see #onCreate(Bundle)
	 * @see #setContentView()
	 * @see #inflateBinding(LayoutInflater)
	 */
	protected abstract void onLoadedLayout();
	
	/**
	 * Determines whether the activity's screen orientation should be locked to
	 * portrait mode. Subclasses must implement this method to provide the decision
	 * logic based on app configuration, device form factor, or user preferences.
	 *
	 * <p><strong>Usage context:</strong>
	 * This method is called from {@link #applyOrientationLock()} during activity
	 * creation. If it returns {@code true}, the activity's requested orientation is
	 * set to {@link android.content.pm.ActivityInfo#SCREEN_ORIENTATION_PORTRAIT}.
	 * If it returns {@code false}, no orientation change is enforced, allowing the
	 * system to rotate freely based on device sensors and user settings.
	 *
	 * <p><strong>Design consideration:</strong>
	 * Locking orientation to portrait may degrade the user experience on tablets or
	 * foldable devices. Subclasses should consider checking device dimensions or
	 * configuration flags before returning {@code true}. Returning {@code false} for
	 * large-screen devices is generally recommended.
	 *
	 * @return {@code true} to lock the activity to portrait orientation,
	 * {@code false} to allow the default orientation behavior.
	 * @see #applyOrientationLock()
	 * @see #setRequestedOrientation(int)
	 */
	protected abstract boolean shouldLockOrientation();
	
	/**
	 * Attaches the base context to the activity after applying saved language preferences.
	 * This method intercepts the base context before it is attached to the activity,
	 * delegates to {@link LocaleHelper#applySavedLanguage(Context)} to obtain a
	 * context with the user's preferred language, and then delegates to the activity's
	 * delegate for any additional attachment processing.
	 *
	 * <p><strong>Implementation note:</strong>
	 * The call to {@code getDelegate().attachBaseContext2(localizedContext)} is required
	 * for proper compatibility with modern Android versions, particularly when using
	 * {@link androidx.appcompat.app.AppCompatDelegate}. This pattern ensures that
	 * the language change persists across configuration changes.
	 *
	 * @param newBase The base context provided by the system before attachment.
	 * @see LocaleHelper#applySavedLanguage(Context)
	 * @see #getDelegate()
	 */
	@Override
	protected void attachBaseContext(Context newBase) {
		Context localizedContext = LocaleHelper.applySavedLanguage(newBase);
		super.attachBaseContext(getDelegate().attachBaseContext2(localizedContext));
	}
	
	/**
	 * Handles configuration changes at runtime, such as screen rotation, locale changes,
	 * or system UI mode changes. This method delegates theme-related processing to the
	 * activity delegate via {@code applyDayNight()}, logs the current night mode state
	 * for debugging purposes, and then chains to the superclass implementation.
	 *
	 * <p><strong>Night mode detection:</strong>
	 * The method extracts the night mode flag from the {@link android.content.res.Configuration#uiMode}
	 * field using the mask {@link android.content.res.Configuration#UI_MODE_NIGHT_MASK}.
	 * If the value equals {@link android.content.res.Configuration#UI_MODE_NIGHT_YES},
	 * the device is currently in dark theme mode. This information is logged at debug
	 * level for monitoring theme transitions.
	 *
	 * <p><strong>Important:</strong>
	 * This method does not recreate the activity. The delegate's {@code applyDayNight()}
	 * method typically forces a recreation or applies theme changes dynamically. Ensure
	 * that the activity has {@code configChanges="uiMode"} declared in the manifest
	 * to receive these callbacks.
	 *
	 * @param newConfig The new configuration object containing updated system settings.
	 * @see #getDelegate()
	 * @see android.content.res.Configuration#UI_MODE_NIGHT_MASK
	 * @see android.content.res.Configuration#UI_MODE_NIGHT_YES
	 */
	@Override
	public void onConfigurationChanged(@NonNull Configuration newConfig) {
		super.onConfigurationChanged(newConfig);
		getDelegate().applyDayNight();
		logger.debug("Activity configuration has changed. Night mode is: " +
			((newConfig.uiMode & Configuration.UI_MODE_NIGHT_MASK)
				== Configuration.UI_MODE_NIGHT_YES));
	}
	
	/**
	 * Initializes the activity during creation. This lifecycle method applies orientation
	 * locking, registers a global crash handler, validates required application
	 * directories, inflates the content view, and executes post-layout initialization.
	 *
	 * <p><strong>Execution order:</strong>
	 * Orientation lock is applied before {@code super.onCreate()} to ensure the screen
	 * rotation setting takes effect before any system processing. Crash handler
	 * registration occurs early to catch any exceptions thrown during subsequent
	 * initialization steps. Directory validation failures are logged but do not crash
	 * the activity.
	 *
	 * @param savedInstanceState Previously saved state data, or {@code null} if the
	 *                           activity is being created fresh. Passed to the superclass
	 *                           for standard restoration handling.
	 * @see #applyOrientationLock()
	 * @see #validateAppDirectories()
	 * @see #setContentView()
	 * @see #onLoadedLayout()
	 */
	@Override
	protected void onCreate(@Nullable Bundle savedInstanceState) {
		applyOrientationLock();
		super.onCreate(savedInstanceState);
		validateAppDirectories();
		setContentView();
		onLoadedLayout();
	}
	
	/**
	 * Locks the activity's screen orientation to portrait mode if the orientation lock
	 * condition is met. This method is called early in {@link #onCreate(Bundle)} to
	 * ensure the orientation setting is applied before the activity's UI is rendered.
	 *
	 * <p><strong>Note:</strong>
	 * The {@code @SuppressLint("SourceLockedOrientationActivity")} annotation suppresses
	 * the Android lint warning about using fixed orientation, which may be undesirable
	 * for certain device form factors (e.g., foldables, tablets). Use this method only
	 * when portrait orientation is strictly required for the UI layout to function.
	 *
	 * @see #shouldLockOrientation()
	 * @see android.content.pm.ActivityInfo#SCREEN_ORIENTATION_PORTRAIT
	 * @see #setRequestedOrientation(int)
	 */
	@SuppressLint("SourceLockedOrientationActivity")
	private void applyOrientationLock() {
		if (shouldLockOrientation()) {
			int screenOrientationPortrait = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
			setRequestedOrientation(screenOrientationPortrait);
		}
	}
	
	/**
	 * Validates that all required application directories exist and are accessible.
	 * This method delegates to {@link AppDirsValidator#performValidation()} which
	 * typically creates or checks directories such as cache, files, and external
	 * storage paths needed for app operation.
	 *
	 * <p><strong>Error handling:</strong>
	 * Any exception thrown during validation (e.g., insufficient storage, permission
	 * denial, or file system errors) is caught and logged via {@code logger.error()}
	 * without rethrowing. This prevents a directory validation failure from crashing
	 * the activity, though subsequent file operations may fail.
	 *
	 * @see AppDirsValidator#performValidation()
	 * @see #onCreate(Bundle)
	 */
	private void validateAppDirectories() {
		try {
			AppDirsValidator.performValidation();
		} catch (Exception error) {
			logger.error("Failed to validate app dirs", error);
		}
	}
	
	/**
	 * Inflates the activity's layout using a view binding pattern and sets it as the
	 * content view. This method retrieves the binding instance via the abstract
	 * {@link #inflateBinding(LayoutInflater)} method, which must be implemented by
	 * subclasses to provide the specific binding type for the activity's layout.
	 *
	 * <p><strong>Usage pattern:</strong>
	 * The binding instance is stored in a protected field (typically named {@code binding})
	 * and provides type-safe access to the layout's views. After calling this method,
	 * the activity's UI hierarchy is fully inflated and ready for view initialization
	 * in {@link #onLoadedLayout()}.
	 *
	 * @see #inflateBinding(LayoutInflater)
	 * @see #setContentView(android.view.View)
	 * @see #onLoadedLayout()
	 */
	private void setContentView() {
		binding = inflateBinding(getLayoutInflater());
		setContentView(binding.getRoot());
	}
	
	/**
	 * Triggers a haptic feedback vibration with a fixed duration of 30 milliseconds.
	 * This method is a convenience wrapper around {@link #vibrate(long)} specifically
	 * designed for button press feedback. The short duration produces a subtle tactile
	 * response suitable for UI interactions without being intrusive to the user.
	 *
	 * <p><strong>Requirements:</strong>
	 * The {@link android.Manifest.permission#VIBRATE} permission must be declared in
	 * {@code AndroidManifest.xml}. If the device lacks vibrator hardware or the
	 * permission is denied, this method will fail silently with a logged error.
	 *
	 * @see #vibrate(long)
	 * @see #vibrate()
	 */
	public void buttonVibrate() {
		vibrate(30);
	}
	
	/**
	 * Triggers a haptic feedback vibration with the default duration of 20 milliseconds.
	 * This parameterless overload delegates to {@link #vibrate(long)} and is suitable
	 * for standard UI feedback scenarios where a moderate, perceptible pulse is desired.
	 *
	 * <p><strong>Usage note:</strong>
	 * The default duration of 20 milliseconds balances perceptibility with power
	 * efficiency. For shorter feedback (e.g., keyboard taps) or longer feedback
	 * (e.g., error alerts), call {@link #vibrate(long)} directly with a custom value.
	 *
	 * @see #vibrate(long)
	 * @see #buttonVibrate()
	 */
	protected void vibrate() {
		vibrate(20);
	}
	
	/**
	 * Performs a single-shot vibration for the specified duration using the modern
	 * {@link android.os.VibrationEffect} API. This method handles cross-version
	 * compatibility: on Android S (API 31+) it retrieves the default vibrator via
	 * {@link android.os.VibratorManager}, falling back to the legacy
	 * {@link android.os.Vibrator} service on older platform versions.
	 *
	 * <p><strong>Implementation details:</strong>
	 * The method creates a {@link VibrationEffect#createOneShot(long, int)} with
	 * {@code DEFAULT_AMPLITUDE} intensity. If no vibrator hardware exists or the
	 * vibrator is unavailable, the method returns silently. All exceptions are caught
	 * and logged via {@code logger.error()} without rethrowing, preventing crashes.
	 *
	 * <p>The {@code @SuppressWarnings("deprecation")} annotation suppresses warnings
	 * related to obtaining the legacy {@link android.os.Vibrator} service, which
	 * remains necessary for pre-API 26 compatibility in this implementation.
	 *
	 * @param duration The vibration duration in milliseconds. Typical values range
	 *                 from 10 to 1000 ms. Negative values will be rejected by
	 *                 {@link VibrationEffect#createOneShot(long, int)} and logged.
	 * @see android.Manifest.permission#VIBRATE
	 * @see android.os.VibrationEffect#createOneShot(long, int)
	 * @see android.os.Vibrator#hasVibrator()
	 * @see #vibrate()
	 * @see #buttonVibrate()
	 */
	@SuppressWarnings("deprecation") protected void vibrate(long duration) {
		try {
			Vibrator vibrator;
			if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
				Object systemService = getSystemService(Context.VIBRATOR_MANAGER_SERVICE);
				VibratorManager vibratorManager = (VibratorManager) systemService;
				vibrator = (vibratorManager != null) ? vibratorManager.getDefaultVibrator() :
					(Vibrator) getSystemService(Context.VIBRATOR_SERVICE);
			} else {
				vibrator = (Vibrator) getSystemService(Context.VIBRATOR_SERVICE);
			}
			
			if (vibrator != null && vibrator.hasVibrator()) {
				int defaultAmplitude = VibrationEffect.DEFAULT_AMPLITUDE;
				VibrationEffect oneShot = VibrationEffect.createOneShot(duration, defaultAmplitude);
				vibrator.vibrate(oneShot);
			}
		} catch (Exception error) {
			logger.error("Failed to vibrate", error);
		}
	}
	
	/**
	 * Determines whether the app has been granted the
	 * {@link android.Manifest.permission#POST_NOTIFICATIONS} permission on Android 13
	 * (API 33) and higher. On older Android versions (API 32 and below), notification
	 * posting is allowed by default without requiring an explicit permission grant.
	 *
	 * <p><strong>Usage pattern:</strong>
	 * Always check this method before calling {@link #requestForNotificationPermission()}
	 * to avoid prompting the user unnecessarily. On API 33+, if this returns {@code false},
	 * you must request the permission. On older platforms, no request is needed.
	 *
	 * @return {@code true} if notifications can be posted (granted on API 33+ or
	 * device runs API 32 or lower), {@code false} if denied on API 33+.
	 * @see #requestForNotificationPermission()
	 * @see android.Manifest.permission#POST_NOTIFICATIONS
	 */
	protected boolean isNotificationPermissionAllowed() {
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
			String postNotifications = Manifest.permission.POST_NOTIFICATIONS;
			return ContextCompat.checkSelfPermission(this, postNotifications)
				== PackageManager.PERMISSION_GRANTED;
		}
		return true;
	}
	
	/**
	 * Requests the {@link android.Manifest.permission#POST_NOTIFICATIONS} permission from
	 * the user. This method is effective only on Android 13 (API 33) and higher, where
	 * the permission was introduced. On older platform versions, the method performs
	 * no operation because notifications are allowed by default.
	 *
	 * <p><strong>Expected workflow:</strong>
	 * Invoke this method only after {@link #isNotificationPermissionAllowed()} returns
	 * {@code false} on API 33+. Permission results are delivered to
	 * {@link android.app.Activity#onRequestPermissionsResult(int, String[], int[])}.
	 * If the user denies the permission, subsequent attempts may show a dialog with
	 * "Never ask again" option, after which further requests are ignored.
	 *
	 * @see #isNotificationPermissionAllowed()
	 * @see android.Manifest.permission#POST_NOTIFICATIONS
	 * @see androidx.core.app.ActivityCompat#requestPermissions
	 */
	protected void requestForNotificationPermission() {
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
			String postNotifications = Manifest.permission.POST_NOTIFICATIONS;
			ActivityCompat.requestPermissions(this,
				new String[]{postNotifications}, REQUEST_CODE_POST_NOTIFICATIONS);
		}
	}
	
	/**
	 * Checks whether legacy external storage permissions are granted on devices running
	 * Android versions below Tiramisu (API 33). This method verifies both
	 * {@link android.Manifest.permission#READ_EXTERNAL_STORAGE} and
	 * {@link android.Manifest.permission#WRITE_EXTERNAL_STORAGE} using
	 * {@link androidx.core.content.ContextCompat#checkSelfPermission}.
	 *
	 * <p><strong>Platform behavior:</strong>
	 * On Android 13 (API 33) and higher, these legacy permissions are deprecated and
	 * considered automatically granted for apps targeting modern SDK versions, so this
	 * method unconditionally returns {@code true}. For older platform versions, both
	 * permissions must be explicitly granted by the user.
	 *
	 * @return {@code true} if storage permissions are granted or not required (API 33+),
	 * {@code false} if either read or write permission is denied on API 32 or lower.
	 * @see #requestForStoragePermission()
	 * @see android.os.Build.VERSION_CODES#TIRAMISU
	 */
	protected boolean isStoragePermissionAllowed() {
		if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
			int readPermission = ContextCompat.checkSelfPermission(this,
				Manifest.permission.READ_EXTERNAL_STORAGE);
			int writePermission = ContextCompat.checkSelfPermission(this,
				Manifest.permission.WRITE_EXTERNAL_STORAGE);
			return readPermission == PackageManager.PERMISSION_GRANTED &&
				writePermission == PackageManager.PERMISSION_GRANTED;
		}
		return true;
	}
	
	/**
	 * Requests legacy external storage permissions for devices running Android 12 (API 32)
	 * or lower. This method displays a system permission dialog asking the user to grant
	 * both {@link android.Manifest.permission#READ_EXTERNAL_STORAGE} and
	 * {@link android.Manifest.permission#WRITE_EXTERNAL_STORAGE} simultaneously.
	 *
	 * <p><strong>Important limitations:</strong>
	 * On Android 11 (API 30) and higher, even with these permissions granted, access is
	 * restricted to app-specific directories and media collections via
	 * {@link android.provider.MediaStore}. For broad file access on API 30+, use
	 * {@link #requestForAllFilesAccess()} instead. On Android 13 (API 33+), this method
	 * performs no operation.
	 *
	 * @see #isStoragePermissionAllowed()
	 * @see #requestForAllFilesAccess()
	 * @see androidx.core.app.ActivityCompat#requestPermissions
	 */
	protected void requestForStoragePermission() {
		if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
			String[] permissions = {
				Manifest.permission.READ_EXTERNAL_STORAGE,
				Manifest.permission.WRITE_EXTERNAL_STORAGE
			};
			ActivityCompat.requestPermissions(this,
				permissions, REQUEST_CODE_STORAGE_PERMISSION);
		}
	}
	
	/**
	 * Determines whether the app has been granted full file system access via the
	 * {@link android.Manifest.permission#MANAGE_EXTERNAL_STORAGE} permission. This method
	 * delegates to {@link FileStorageUtility#hasFullFileSystemAccess(Context)} for the
	 * actual permission verification logic.
	 *
	 * <p><strong>Use case:</strong>
	 * Full file system access (also known as "All Files Access") allows the app to read
	 * and write all files on external storage, including those belonging to other apps.
	 * This permission is required on Android 11 (API 30) and higher for file management,
	 * antivirus, or backup operations that cannot be accomplished using scoped storage.
	 *
	 * @return {@code true} if the app has full file system access, {@code false} otherwise.
	 * @see #requestForAllFilesAccess()
	 * @see android.os.Environment#isExternalStorageManager()
	 * @see FileStorageUtility#hasFullFileSystemAccess(Context)
	 */
	protected boolean isAllFilesAccessAllowed() {
		Context applicationContext = getApplicationContext();
		return FileStorageUtility.hasFullFileSystemAccess(applicationContext);
	}
	
	/**
	 * Requests the MANAGE_EXTERNAL_STORAGE permission, which grants broad access to all
	 * files on shared external storage. This method first attempts to launch the
	 * platform's settings page for the app-specific "All Files Access" permission using
	 * {@link android.provider.Settings#ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION}.
	 *
	 * <p><strong>Fallback behavior:</strong>
	 * If the specific intent fails (e.g., on older Android versions or custom ROMs),
	 * the method catches the exception and falls back to the generic intent
	 * {@link android.provider.Settings#ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION}.
	 * The fallback intent does not pre-fill the package name, requiring the user to
	 * manually locate this app in the settings UI.
	 *
	 * @see #isAllFilesAccessAllowed()
	 * @see android.provider.Settings#ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION
	 */
	protected void requestForAllFilesAccess() {
		try {
			Intent intent = new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION);
			intent.addCategory("android.intent.category.DEFAULT");
			intent.setData(Uri.parse(String.format("package:%s", getPackageName())));
			startActivity(intent);
		} catch (Exception error) {
			logger.error("Error requesting all file access: ", error);
			Intent intent = new Intent();
			intent.setAction(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION);
			startActivity(intent);
		}
	}
	
	/**
	 * Determines whether the app is permitted to install packages from unknown sources.
	 * This method delegates to {@link android.content.pm.PackageManager#canRequestPackageInstalls()}
	 * and reflects the user's current grant state for the
	 * {@link android.Manifest.permission#REQUEST_INSTALL_PACKAGES} permission.
	 *
	 * <p><strong>Usage pattern:</strong>
	 * Always invoke this method before attempting an APK installation. If {@code false},
	 * call {@link #requestForInstallPackages()} to redirect the user to the system
	 * settings screen. The permission state may change when the user returns to the
	 * app, so re-check in {@link android.app.Activity#onResume()} after the intent.
	 *
	 * @return {@code true} if the app can request package installs, {@code false} otherwise.
	 * @see #requestForInstallPackages()
	 * @see android.Manifest.permission#REQUEST_INSTALL_PACKAGES
	 */
	protected boolean isInstallPackagesAllowed() {
		return getPackageManager().canRequestPackageInstalls();
	}
	
	/**
	 * Launches the system settings screen that allows the user to grant the
	 * {@link android.Manifest.permission#REQUEST_INSTALL_PACKAGES} permission.
	 * The intent is constructed with a {@code package} URI scheme pointing to this
	 * app's package name, ensuring the settings UI opens directly on the correct
	 * management page rather than showing a generic list of apps.
	 *
	 * <p><strong>Expected workflow:</strong>
	 * Call this method only after {@link #isInstallPackagesAllowed()} returns {@code false}.
	 * The user's selection is not delivered via {@code onActivityResult()}. Instead,
	 * override {@link android.app.Activity#onResume()} and re-check
	 * {@link #isInstallPackagesAllowed()} to determine if the permission was granted.
	 *
	 * @see android.provider.Settings#ACTION_MANAGE_UNKNOWN_APP_SOURCES
	 * @see #isInstallPackagesAllowed()
	 */
	protected void requestForInstallPackages() {
		Uri packageUri = Uri.parse("package:" + getPackageName());
		Intent intent = new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES, packageUri);
		startActivity(intent);
	}
}
